---

- name: configure postgre SQL instance
  hosts: "{{ pgnode1 }}"
  remote_user: "ubuntu"
  become: yes
  serial: 1
  vars:
    ansible_ssh_private_key_file: secrets/ssh-keys/test-cloud
    ansible_python_interpreter: /usr/bin/python
  roles:
    - role: postgress_deploy
